### ISSUE TITLE
RuntimeError: Failed to import pydot.

### ISSUE THREAD

**Issue by mattdornfeld** [Theano/Theano#1801]
I just tried running this example http://deeplearning.net/software/theano/tutorial/printing_drawing.html for printing theano graphs from ipython, and I got this error. Anyone possibly know why? If I try accessing theano.printing.pydotprint, it has no trouble finding the attribute.

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-195-249903233dc8> in <module>()
>      70 theano.printing.pydotprint(predict,
>      71                            outfile="pics/logreg_pydotprint_predic.png",
> ---> 72                            var_with_name_simple=True)
>      73 # before compilation
>      74 theano.printing.pydotprint_variables(prediction,
> /usr/local/lib/python2.7/dist-packages/theano/printing.pyc in pydotprint(fct, outfile, compact, format, with_ids, high_contrast, cond_highlight, colorCodes, max_label_size, scan_graphs, var_with_name_simple, print_output_file, assert_nb_all_strings)
>     566 
>     567     if not pydot_imported:
> --> 568         raise RuntimeError("Failed to import pydot. You must install pydot"
>     569                             " for `pydotprint` to work.")
>     570         return

**Comment by bugkiwi** [comment]
@chrischoy `brew install graphviz` fix my problems! Thank you :)

**Comment by bugkiwi** [comment]
@coralzhang 
You should install a C-version graphviz,like `brew install graphviz` on mac;
and after that you can get some graphviz info  like
```
print pydot.find_graphviz()
{'fdp': '/usr/local/bin/fdp', 'twopi': '/usr/local/bin/twopi', 'neato': '/usr/local/bin/neato', 'dot': '/usr/local/bin/dot', 'circo': '/usr/local/bin/circo'}
```

**Comment by uclyyu** [comment]
Anyone here using python 3.4.x? 

I am having the same issue on Ubuntu 15.04. 
Having followed through the instructions above: `apt-get install graphviz` and `pip3 install pydot`.
The `pydot` installation doesn't work for me, possibly not python 3.x compatible. 

So I switched to `pip3 install pydot3k`, which gives:
```
import pydot

print(pydot.find_graph())
{'circo': '/usr/bin/circo',
 'dot': '/usr/bin/dot',
 'fdp': '/usr/bin/fdp',
 'neato': '/usr/bin/neato',
 'sfdp': '/usr/bin/sfdp',
 'twopi': '/usr/bin/twopi'}
```
Unfortunately, the same issue mentioned by @coralzhang persists. Any ideas? 

Many thanks!

**Comment by nouiz** [comment]
The python 3 compatible version of pydot is called pydot-ng. Try to install
that one and use Theano development version.

**Comment by windweller** [comment]
This is awesome! I was having a similar problem and did not realize to install C package at all.
Thanks @nouiz !!

**Comment by lce-fr** [comment]
Hi ! 

I just faced the problem because I had pydot but not graphviz (facepalm). I think that the exception 
"Failed to import pydot. You must install pydot" is misleading. The exception can be raised for two reasons (cf start of printing.py) : 

  - You do not have pydot
  - You have pydot and not graphviz. In this case, you read the exception and try to import pydot but nothing goes wrong since it can be imported without graphviz installed.

Thereforefore, the exception could be clearer with "you must install pydot and graphviz"

Kind regards,
Laurent

**Comment by carlthome** [comment]
Had the same issue with missing graphviz and it took me longer to fix than it should have since I had to look at the Theano source to understand what was wrong. The ImportError is really misleading.

**Comment by nouiz** [comment]
In the master of Theano, the error is:

Failed to import pydot. You must install pydot and graphviz for
`pydotprint` to work.

What do you suggest we tell? It already tell that graphviz must be there.
If you have better message to add, we can change it.

thanks

**Comment by carlthome** [comment]
The same clarification could be added here as well: https://github.com/Theano/Theano/blob/458e1594c9407ac1fd2a7b6751c6ee2385c5d33f/theano/d3viz/formatting.py#L54

**Comment by nouiz** [comment]
Good find. Do you want to make a PR and have your name in the history of
git commit of Theano?

Otherwise, I can do it.

**Comment by carlthome** [comment]
Yey, the epic commit history! I'll do a pr now. :+1:

**Comment by jskDr** [comment]
brew install graphviz
which I did to resolve this issue.

**Comment by Roboball** [comment]
what is the command for cmd, windows user (win7)?

i tried pip install graphviz, in cmd it is installed, but in spyder I get the result none.

**Comment by nouiz** [comment]
It seem spyder don't use the same python as the default one for your OS. I don't use spyder, so I can't help more then tell to check which python spyder is using and install it for that python version with pip. Use the pip in the same folder as the python version that spyder use.

**Comment by anujgupta82** [comment]
I seeming to be still facing this issue. 

Did the 3 steps 
1. brew install graphviz
2. pip install pydot
3. pip install graphviz

When I do : 
`import pydot
print pydot.find_graphviz()`

I get "AttributeError: 'module' object has no attribute 'find_graphviz"
I tried http://stackoverflow.com/questions/38446771/importing-theano-attributeerror-module-object-has-no-attribute-find-graphvi
but still getting the error
"AttributeError: 'module' object has no attribute 'find_graphviz"

**Comment by nouiz** [comment]
Newer pydot version don't have that attribute anymore.

Use THeano dev version, we accept newer pydot version now.

**Comment by luango3110** [comment]
I have similar error when I run 
"from keras.utils.visualize_util import plot"


File "C:\Users\Lua\Anaconda2\lib\site-packages\keras-1.1.1-py2.7.egg\keras\utils\visualize_util.py", line 12, in <module>
    raise RuntimeError('Failed to import pydot. You must install pydot'

RuntimeError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.


I can import pydot, graphviz, and theano.
When I ran "pydot.find_graphviz()": 
Traceback (most recent call last):

  File "<ipython-input-12-97d9c276b23b>", line 1, in <module>
    pydot.find_graphviz()

AttributeError: 'module' object has no attribute 'find_graphviz'

I tried several pydot versions (pydot 1.2.3, pydot-ng, pydot 1.2.2, and pydot 1.1.0), and graphviz versions (0.5.1 by pip install, 2.38.0-2 by anaconda), but nothing worked.
I use anaconda 4.1.1, python 2.7 in win 10 64-bit (the code was ran in spyder).

Thank you in advance.

**Comment by linboqiao** [comment]
sudo apt-get install graphviz
pip install graphviz
pip install pydot==1.1.0

It works on Ubuntu 16.04.

**Comment by sookinoby** [comment]
for windows, please see this.

https://stackoverflow.com/questions/36886711/keras-runtimeerror-failed-to-import-pydot-after-installing-graphviz-and-pyd/36890526#36890526

http://stackoverflow.com/questions/36869258/how-to-use-graphviz-with-anaconda-spyder

**Comment by Switpok** [comment]
pip install pydot-ng and brew install graphviz worked for me :) 

- Thanks!

**Comment by mahernadar** [comment]
Hey guys :)

I am on ubuntu 16.04, working with jupyter notebook with keras and Tensorflow backend.

when i install pyplot using "sudo apt-get install pyplot" i get:

"Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pyplot"

and naturally, when i run " from keras.utils import plot_model
                                          plot_model(model, to_file='model.png')"

inside the notebook, i get the following error:
"ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work."

How do i correctly install the pyplot and graphviz?

Thanks :)

**Comment by hlpassion** [comment]
brew install graphviz 
solve my problem. THX everyone

**Comment by Oxi84** [comment]
Btw I still have the same problem ... I am trying to install graphviz on windows, and I did install the windows version of the software (https://graphviz.gitlab.io/_pages/Download/Download_windows.html)  but i do not know what to do with the patch in order to make it work.
I get exception when I do:
print pydot.find_graphviz()

Pydot import does work,

**Comment by cristinabustos16** [comment]
I was able to solve it like this:

sudo apt-get install graphviz
pip install pydot
pip install graphviz

**Comment by Oxi84** [comment]
On linux it is easy, but for windows it is more dificult.

**Comment by nouiz** [comment]
I think conda version of pydot or pydot-ng include graphviz.

**Comment by muradalqurishee10** [comment]
I solve it in this video.
https://www.youtube.com/watch?v=W_Ioq6l77P0
