### ISSUE TITLE
Unable to import theano on OS X 10.11

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Theano/Theano#3502]
Hi

I am having a hard time getting `theano` to work in Python 3.5 in OS X (El Capitan).

with:
```
$ python --version

Python 3.5.0 :: Continuum Analytics
```

* [Here](https://gist.github.com/amelio-vazquez-reina/0850909dc01f9c84d134) is my `pip freeze`
* [Here](https://gist.github.com/amelio-vazquez-reina/fbb031db3615451f1465) is the error that I run into when importing it. 

The error ends with:

```
 Exception: Compilation failed (return status=1): clang: error: unsupported argument '-q' to option 'Wa,'.
```

Any thoughts on what could explain it?

**Comment by nouiz** [comment]
This is a problem with that OS X version that isn't supported by NVIDIA. There is already a ticket about this:

https://github.com/Theano/Theano/issues/3415

So I'll close this one. Look at that ticket and continue discussion there is needed. There is some URL there with some workaround.

**Comment by abergeron** [comment]
This is our problem since that does not go through nvcc.  We are passing -Wa,-q which we shouldn't.

**Comment by nouiz** [comment]
There is another report related to that somewhere.

2 possibles fix, if you have numpy 1.10, downgrade to numpy 1.9.2.

If that don't do it, downgrad to python 3.4.

Tell us what fix it.

Don't update your mac if you want to use the GPU. The last mac version
isn't supported by NVIDIA and some ugly work around are needed:

https://github.com/Theano/Theano/issues/3415

**Comment by abergeron** [comment]
It's possible that downgrading to python 3.4 will work, but I highly doubt that downgrading numpy will change anything.

If downgrading python does not work, then someone would have to trace through the compiling procedure to figure out where it's adding that flag and why.

**Comment by amelio-vazquez-reina** [comment]
Thanks all. Downgrading to Python 3.4 did not change things, unfortunately (gist [here](https://gist.github.com/amelio-vazquez-reina/92b7a17b91b463712c54), `pip freeze` [here](https://gist.github.com/amelio-vazquez-reina/71c099ea2dc8153fd1c9))

**Comment by amelio-vazquez-reina** [comment]
And downgrading both Python to `3.4` and  numpy `1.9.2` didn't fix it either (gist [here](https://gist.github.com/amelio-vazquez-reina/1e77a55aa4ce34cf8f5b)).

**Comment by amelio-vazquez-reina** [comment]
@nouiz Do you now if nVidia has fix the problem? How do we know the problem I reported above is related to it?

**Comment by amelio-vazquez-reina** [comment]
@abergeron Is there anything I can help to better diagnose the problem? You mentioned:

> This is our problem since that does not go through nvcc. We are passing -Wa,-q which we shouldn't.

Happy to investigate this in any way I can.

**Comment by abergeron** [comment]
It seems this has fallen a bit through the cracks.

I'm able to import the current master of Theano on 10.11 with python 3.4.4 so I figure the problem has been fixed.  Can you confirm?

**Comment by amelio-vazquez-reina** [comment]
It all works now. I was able to import and run code from other libraries (e.g. [PyMC3](https://github.com/pymc-devs/pymc3)) that depend on Theano. Thanks!
