### ISSUE TITLE
Compilation error (unrecognized option -m32) option on arm with 0.6.0 Theano

### ISSUE THREAD

**Issue by olegsinavski** [Theano/Theano#1856]
Hello,

I started to have the following compilation error on arm architecture after I upgraded from Theano 0.6.0rc3 to 0.6.0. 

```
...
01042        m = Py_InitModule3("lazylinker_ext", lazylinker_ext_methods,
01043                           "Example module that creates an extension type.");
01044    #endif
01045        Py_INCREF(&lazylinker_ext_CLazyLinkerType);
01046        PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01047   
01048        return RETVAL;
01049    }
01050   
01051   
===============================
cc1plus: error: unrecognized command line option '-m32'
Problem occurred during compilation with the command line below:
g++ -shared -g -march=armv7-a -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m32 -fPIC -I/home/ubuntu/projects/lego/venv/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -o /home/ubuntu/.theano/compiledir_Linux-3.0.21-perf+-armv7l-with-Ubuntu-12.04-precise-armv7l-2.7.3-32/lazylinker_ext/lazylinker_ext.so /home/ubuntu/.theano/compiledir_Linux-3.0.21-perf+-armv7l-with-Ubuntu-12.04-precise-armv7l-2.7.3-32/lazylinker_ext/mod.cpp -L/usr/lib -lpython2.7
```

Any ideas how to debug/fix this? I'm amateur in Thean compilation filed and I'm not even sure where to start here..
