### ISSUE TITLE
error compiling gof (lazylinker_ext.pyd missing)?

### ISSUE THREAD

**Issue by dattienhoang** [Theano/Theano#5803]
Hello,

I'm on a 64-bit Windows 10 machine using Python 2.7 (Anaconda2). I don't receive any errors when installing Theano with conda, but when I try to import in Python, I get the following message:

```
===============================
g++.exe: error: Tien: No such file or directory
g++.exe: error: Hoang\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd: No such file or directory
g++.exe: error: C:\Users\Dat: No such file or directory
g++.exe: error: Tien: No such file or directory
g++.exe: error: Hoang\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory


```

At first, I thought it was maybe because I have a space in my username, but saw a previous issue had fixed this error already [link](https://github.com/Theano/Theano/issues/5183). This compilation error happens regardless of whether I use the standard install by conda, or following the bleeding-edge installation.

From the errors, it looks like I'm missing a couple files (lazylinker_ext.pyd and mod.cpp), which are not present when I navigate to the specified folder in the error using Windows Explorer. Is there a way to get these files?

What's crazy is that I have previously installed Theano on a different computer successfully using the normal installation method using conda, and can't figure why I'm having problems on a very similar computer!

Any help appreciated,
Dat

**Comment by nouiz** [comment]
The error tell me the problem is still related to spaces in path.

Can you can in pdb at the place of the error and investigate a little bit?
For do one reason the previous fix didn't worked in all cases or this git
broken again. Check how we build the command we execute to compile.

Thanks for your help.

Le dim. 2 avr. 2017 16:13, Dat Tien Hoang <notifications@github.com> a
écrit :

**Comment by dattienhoang** [comment]
hopefully this is what you wanted (not a python expert):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\theano\__init__.py", line 88, in <module>
    from theano.compile import (
  File "C:\Anaconda2\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode
  File "C:\Anaconda2\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm
  File "C:\Anaconda2\lib\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c
  File "C:\Anaconda2\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2339, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): g++.exe: error: Tien: No such file or directory
. g++.exe: error: Hoang\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd: No such file or directory
. g++.exe: error: C:\Users\Dat: No such file or directory
. g++.exe: error: Tien: No such file or directory
. g++.exe: error: Hoang\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp: No such file or directory
```

let me know if it is not!

**Comment by nouiz** [comment]
The problem is that I'm not able to reproduce the error. Do you have time to investigate a little in the code? What we would need is that you put a python break point (import pdb;pdb.set_trace() in the file gof/cmodule.py at the start of the method compile_str(). Then check where do we don't respect the space in the path.

Do you have time for such small investigation?

**Comment by nouiz** [comment]
I just saw the fix in the link you gave wasn't merged upstream. Can you do it manually? I'll put that in a PR

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/5842

**Comment by dattienhoang** [comment]
sorry the late response....everything works now. thanks!

**Comment by ivan-marroquin** [comment]
I am using a windows machine. I have a command line that changes the default path of "compiledir" to a different location (no blank spaces in the folder names). The script used to correctly work in Theano 0.9.0

Now, I have Theano 1.0.1 and when I run the same script, I get this error:

Exception: ('The following error happened while compiling the node', InplaceDimShuffle{x,0}(layer:tanh-1/bias), '\n', 'Compilation failed (return status=1): C:/Temp/Anaconda3/Library/mingw-w64/bin/../
lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\SEG_contest\\Independent_Scripts\\Model_1\
\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.6.1-64\\tmpmy2qwa6b\\m885ff006a95d626dac547a7bdfdb471bbf058622ece2b4435e42316c4012ea56.pyd: No such file or direc
tory\r. collect2.exe: error: ld returned 1 exit status\r. ', '[InplaceDimShuffle{x,0}(layer:tanh-1/bias)]')

It creates the folder: compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineIntel-3.6.1-64\\tmpmy2qwa6b\

but there is only a mod file. The pyd file is missing plus other files/folders (see attachment).

Any suggestions?

Many thanks,
Ivan

![theano_files](https://user-images.githubusercontent.com/28459534/39638378-a60c8ce2-4f8b-11e8-9473-61ced0b5c474.PNG)

**Comment by nouiz** [comment]
Some other user had a similar problem due to windows maximum file path of 255 characters.

Defining a shorter compiledir name could help you.
