### ISSUE TITLE
BNComposite has no attribute _c_code

### ISSUE THREAD

**Issue by mpslxz** [Theano/Theano#5816]
After upgrading to v0.9 from rc, I cannot load pickles if the model has batch normalization calls. 

> theano/scalar/basic.py", line 4032, in __setstate__
    assert self._c_code
AttributeError: 'BNComposite' object has no attribute '_c_code'

**Comment by lamblin** [comment]
I'm pretty sure that line should be removed, now we do not always generate the C code (5930ecd4).
Could you try it, and submit a PR?

**Comment by mpslxz** [comment]
That is right. C code is not always generated. I'm not sure where c_code() function is called, though. Would you elaborate on what you'd like me to try for PR, please?

**Comment by nouiz** [comment]
Can you try this diff:
```
index 9fe81b1..628d263 100644
--- a/theano/scalar/basic.py
+++ b/theano/scalar/basic.py
@@ -4025,7 +4025,6 @@ class Composite(ScalarOp):
         self.prepare_node_called = set()
         self.init_fgraph()
         self.init_py_impls()
-        assert self._c_code
 
 
 class Compositef32(object):
```

thanks

**Comment by nouiz** [comment]
I have this diff in a branch if you prefer: https://github.com/nouiz/Theano/tree/unsigned_char

thanks

**Comment by mpslxz** [comment]
Sure. I'll do it.
