### ISSUE TITLE
Error when importing Theano

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#3327]
Seems to have been introduced by aeb8c035895cf13df42e125fbf784d9e7a913e14.

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "theano/__init__.py", line 103, in <module>
        import theano.sandbox.cuda
      File "theano/sandbox/cuda/__init__.py", line 327, in <module>
        from . import opt, dnn
      File "theano/sandbox/cuda/opt.py", line 2578, in <module>
        compile.optdb.register('local_inplace_gpu_sparse_block_gemv',
    AttributeError: 'builtin_function_or_method' object has no attribute 'optdb'

**Comment by ebenolson** [comment]
Nevermind, I see there is already a PR https://github.com/Theano/Theano/pull/3325 for this.
